### PR TITLE
YAML load needs permitted classes

### PR DESCRIPTION
**Pull request by SocalNick**
# Description:

[Psych v4.0.0](https://github.com/ruby/psych/releases/tag/v4.0.0) changed to safe_load by default

Fixes https://github.com/rubygems/gemstash/issues/323
______________

# Tasks:

x  Describe the problem / feature
x  Write tests

I will abide by the [code of conduct](https://github.com/gemstash/gemstash/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by indirect — APPROVED** [review]
Thank you!

**Comment by olleolleolle** [comment]
> Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.

If you don't get to it, we could take care of it later.

**Comment by SocalNick** [comment]
Thank you all for getting this in so quickly!

**Comment by indirect** [comment]
New version 2.2.1 released! Let us know if you see any other issues. :)

**Pull request merged**
