### PR TITLE
Fix CHANGELOG.md

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
Fix CHANGELOG.md references and version changes
______________

# Tasks:

-  Describe the problem / feature
-  Write tests

I will abide by the [code of conduct](https://github.com/gemstash/gemstash/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by olleolleolle** [comment]
If this is run by a script, this is totally super. 

Some people use the "reference style" of markdown link to point to the contributors. So, a list of links at the bottom, and references to them in the individual changelog lines.

**Comment by olleolleolle** [comment]
And thank you!

**Comment by bronzdoc** [comment]
@olleolleolle yes this is generated with a script, somehow I got it wrong the first time, might be order dependent of the release task I'm not sure. Also is not putting the right version at the top so I had to do that manually 🤷‍♂

**Comment by olleolleolle** [comment]
But you released stuff! :tada:

**Pull request merged**
