### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
 
- Remove Travis ci in favor of Github Actions
- Revert bundler dependency to `~> 1.11` 

I will abide by the [code of conduct](https://github.com/gemstash/gemstash/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by micheelengronne** [comment]
I think the CI hits this problem https://github.com/uraimo/run-on-arch-action/issues/4

**Comment by bronzdoc** [comment]
@micheelengronne thanks for the link I appreciate your help! Maybe we can pair in this issue? are you in the bundler channel? if not I can invite you and we can coordinate if you do like that :)

**Comment by micheelengronne** [comment]
@bronzdoc Yes, I would be interrested. Thank you.

**Comment by bronzdoc** [comment]
@micheelengronne I invited you to the channle with the email of your Github let me know if that is ok or you need me to add you with another email

**Comment by olleolleolle** [comment]
@bronzdoc 👋 I resolved a "conflict with the default branch". 🌞 It's morning here, and I saw that your last "activity" was 5 hours ago. Hope this didn't wreck your plans!

**Comment by micheelengronne** [comment]
Hum @olleolleolle sorry but yes. The idea was to remove the 2 last MR from the master branch because they were buggy.

The conflict with default branch was attended. Can you undo please ?

**Comment by olleolleolle** [comment]
@micheelengronne  Thanks for the sharp eyes 👀 !

I did a revert `git revert 32b7a5a80bdf69a0a63290d6dc22b1141a8a94f2 -m1` and pushed it. Hope this got to where needed.

**Comment by micheelengronne** [comment]
We'll see with @bronzdoc, he is the one full head in that :)

**Comment by olleolleolle** [comment]
@bronzdoc 👋 Hi! Hope you're alright and that things are good where you are.

Can we move forward with this?

**Comment by bronzdoc** [comment]
Sorry for taking that long guys! 

@olleolleolle can you give me a heads up of what happened here? did you add master but without the two PR that were causing issues is that it?

**Comment by bronzdoc** [comment]
I Will get back to this tomorrow

**Comment by olleolleolle** [comment]
Hi! I made a too-quick decision on not enough information, and later learned that one of the goals of this PR was to change history of the default branch, to avoid some commits that had become... wrong. That's my current understanding. 

I won't make any more changes unless you ask me to. 

(I'm writing this on GitHub's Android app, which misattributed comments, at first, which made it look like @bronzdoc had answered with verbatim responses. Apps, gah. Sorry if I emoji'd on the wrong comment, just now!)

**Comment by bronzdoc** [comment]
Ohhh nooo! the evil laugh emoji! 😄 

No worries @olleolleolle, It's not offensive at all, like at all 😂  

My plan was to switch to Github action and fix the spec failures related to the bundler version we use in CI in this PR, then fix the issues introduced by https://github.com/rubygems/gemstash/pull/274 and https://github.com/rubygems/gemstash/pull/270. 

I removed the commits of #274 and #270 here so I could isolate the bundler problems and work around them(which we did) then I was planning to get those commits back and fix those in separate PR's but also open to revert those commits(in a separate PR) and merge them back to master when we fix the issues in each of them.

Let me know what you and @micheelengronne think about this. As always really grateful for your support :)

**Comment by olleolleolle** [comment]
@bronzdoc I think that this is a great way to go, and a good way forward.

**Comment by bronzdoc** [comment]
Specs are expected to fail here since we still have the features we are reverting in https://github.com/rubygems/gemstash/pull/293 after that is merged we could respect a green build again

**Comment by bronzdoc** [comment]
Merged #293 and rebased master, build is green now 🎉  so I will move forward with this PR

**Comment by simi** [comment]
:confetti_ball:

**Pull request merged**
