### PR TITLE
S3 Support

### PR DESCRIPTION
**Pull request by sk-jlewis**
Addresses https://github.com/bundler/gemstash/issues/107
Added two configuration options:
```
+      gem_path: nil,
+      storage_adapter: "Storage",
```

storage_adapter can be "Storage" or "S3".  If "S3" gem_path is the bucket in S3.

This is somewhat quick and dirty, so welcome feedback and support!

### CODE REVIEW

**Comment by CpuID** [comment]
@sk-jlewis one trailing whitespace line to get Travis to stop complaining? https://travis-ci.org/bundler/gemstash/jobs/265394798

```
lib/gemstash/health.rb:11:1: C: Style/TrailingWhitespace: Trailing whitespace detected.
102 files inspected, 1 offense detected
```

:)

**Comment by CpuID** [comment]
Tests almost pass, seems to be jruby only that fails now? I've seen that particular part of the test suite fail under MRI locally myself as well (2.4.x), but it passed on Travis, flaky/inconsistent which is weird...

**Comment by sk-jlewis** [comment]
This test has failed for me since I started work on this branch :/  It failed for me with or without changes

**Comment by CpuID** [comment]
> This test has failed for me since I started work on this branch :/ It failed for me with or without changes

👍

**Comment by sk-jlewis** [comment]
I also didn't add any tests to this and I haven't had much time to add any.  We are however using it successfully (so far ;) )

**Comment by CpuID** [comment]
> We are however using it successfully (so far ;) )

good to hear, I am planning to test it for our own use also, thanks :)

**Comment by CpuID** [comment]
One suggestion feature wise here:

- support prefix based installations in a single S3 bucket
  - example: dev + prod in a single bucket, with keys prefixed accordingly

**Comment by CpuID** [comment]
@sk-jlewis are you using the passthrough rubygems.org proxy support? or only the private gem hosting functionality?

Noticed a lot of 500s with these stack traces when trying to passthrough rubygems.org with a simple example: https://gist.github.com/CpuID/233e5482c8a3486b5d3fcd8393e4777e

(Note this was trimmed down, but the stack traces are pretty much identical with fresh temp filenames for each example).

Config:

```
/ # cat /gemstash-config.yml
---
:base_path: "/gemstash-data"
:gem_path: "ted-conferences-gemstash-dev"
:storage_adapter: "S3"
:cache_type: memcached
:memcached_servers: memcached:11211
:db_adapter: mysql2
:db_url: mysql2://gemstash:REDACTED@mysql:3306/gemstash
:protected_fetch: true
:fetch_timeout: 20
```

My `Gemfile`:

```
source "http://localhost:32818"
gem "json"

source "http://localhost:32818/private" do
  gem "myprivategem"
end
```

The interesting thing: there is a `metadata.yml` file in the S3 bucket root, but no `.metadata.yml*` files. I assume the file names are coincidental and unrelated though (one is a master metadata file, the others are temp metadata files?).

I assume there is some logic trying to use `:gem_path` for cached upstream data, but it won't work in parallel with the S3 bucket configuration using that same config option?

**Comment by CpuID** [comment]
@sk-jlewis getting similar stack traces trying to `gem yank` a private gem also:

```
[2017-09-07 11:49:49 +0000] - ERROR - 2017-09-07 11:49:49 - Errno::ENOENT - No such file or directory @ rb_sysopen - ted-conferences-gemstash/.metadata.yml20170907-25-tp8c5w:
	/usr/local/lib/ruby/2.4.0/tempfile.rb:133:in `initialize'
	/usr/local/lib/ruby/2.4.0/tempfile.rb:133:in `open'
	/usr/local/lib/ruby/2.4.0/tempfile.rb:133:in `block in initialize'
	/usr/local/lib/ruby/2.4.0/tmpdir.rb:130:in `create'
	/usr/local/lib/ruby/2.4.0/tempfile.rb:131:in `initialize'
	/usr/local/lib/ruby/2.4.0/tempfile.rb:291:in `new'
	/usr/local/lib/ruby/2.4.0/tempfile.rb:291:in `open'
	/usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/core_ext/file/atomic.rb:22:in `atomic_write'
	/gemstash/lib/gemstash/storage.rb:67:in `metadata'
	/gemstash/lib/gemstash/storage.rb:79:in `check_storage_version'
	/gemstash/lib/gemstash/storage.rb:27:in `initialize'
	/gemstash/lib/gemstash/storage.rb:56:in `new'
	/gemstash/lib/gemstash/storage.rb:56:in `for'
	/gemstash/lib/gemstash/gem_yanker.rb:41:in `storage'
	/gemstash/lib/gemstash/gem_yanker.rb:59:in `block in update_database'
	/usr/local/bundle/gems/sequel-5.0.0/lib/sequel/database/transactions.rb:204:in `_transaction'
	/usr/local/bundle/gems/sequel-5.0.0/lib/sequel/database/transactions.rb:179:in `block in transaction'
	/usr/local/bundle/gems/sequel-5.0.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
	/usr/local/bundle/gems/sequel-5.0.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	/usr/local/bundle/gems/sequel-5.0.0/lib/sequel/database/connecting.rb:264:in `synchronize'
	/usr/local/bundle/gems/sequel-5.0.0/lib/sequel/database/transactions.rb:145:in `transaction'
	/gemstash/lib/gemstash/gem_yanker.rb:53:in `update_database'
	/gemstash/lib/gemstash/gem_yanker.rb:34:in `serve'
	/gemstash/lib/gemstash/gem_yanker.rb:23:in `serve'
	/gemstash/lib/gemstash/gem_source/private_source.rb:97:in `block in protected'
	/gemstash/lib/gemstash/api_key_authorization.rb:13:in `protect'
	/gemstash/lib/gemstash/gem_source/private_source.rb:97:in `protected'
	/gemstash/lib/gemstash/gem_source/private_source.rb:31:in `serve_yank'
	/gemstash/lib/gemstash/web.rb:46:in `block in <class:Web>'
```

**Comment by sk-jlewis** [comment]
Looks like from the backtrace that its using the "Storage" class instead of the S3 class. 
This function:
```
/gemstash/lib/gemstash/gem_yanker.rb:41:in `storage'
```
Must be returning the wrong kind of storage adapter.

In our gemfiles, we set the source to /private:
```
source 'https://server-domain/private'
```

**Comment by sk-jlewis** [comment]
Fixed in https://github.com/bundler/gemstash/pull/159/commits/15bf10fa4176b57b1ca8fc26fa8946465f148776

**Comment by sk-jlewis** [comment]
@CpuID , I have `protected` set to false in my configurations, not sure if that may be a contributing factor (ours is served behind a VPN).  I'll see if I can take a look later today

**Comment by CpuID** [comment]
@sk-jlewis confirmed https://github.com/bundler/gemstash/commit/15bf10fa4176b57b1ca8fc26fa8946465f148776 fixes yanking, thanks :)

Re the issue with rubygems.org proxying above, would simply replacing:

```
@storage ||= Gemstash::Storage.for("gem_cache")
```

with:

```
@storage ||= gemstash_env.storage_adapter_class.for("gem_cache")
```

in gem_source/upstream_source.rb do the trick? Untested, just a theory. Would using `.for("gem_cache")` differ much from `.for("private").for("gems")`?

**Comment by CpuID** [comment]
@sk-jlewis thx for https://github.com/bundler/gemstash/pull/159/commits/23082f4113839b4dfa7c87c1a4ee47144d5bd839 - confirmed that rubygems.org proxying now works without erroring out.

**Comment by sk-jlewis** [comment]
woohoo!

**Comment by caius** [comment]
I fixed up the test failures, turns out one of the fixes for swapping out the storage had forgotten to append enough to the storage path, so we were looking for files in a different place to where they'd been cached.

https://github.com/caius/gemstash/commit/3ae4520eee3de2f2ef1156907bdc2c2c430877df fixes it, and I get a clean test run on this branch with that commit applied.

@sk-jlewis what's the easiest way for you to pull that fix in - do you want me to raise a PR against your fork for it? (My branch also merges master in, because why not. Few changes there but nothing else breaks as far as I've seen in testing.)

**Comment by sk-jlewis** [comment]
not totally sure i follow
> @sk-jlewis what's the easiest way for you to pull that fix in - do you want me to raise a PR against your fork for it? (My branch also merges master in, because why not. Few changes there but nothing else breaks as far as I've seen in testing.)

Could I just rebase from master and apply your commit?

**Comment by caius** [comment]
That works for me!

Cheers for the original work, very useful!

C
---
Caius Durling
Transmitted from my handheld supercomputer
caius@caius.name
+44 (0) 7960 268 100
http://caius.name/

On 26 Sep 2017, at 17:28, sk-jlewis <notifications@github.com> wrote:

not totally sure i follow

@sk-jlewis <https://github.com/sk-jlewis> what's the easiest way for you to
pull that fix in - do you want me to raise a PR against your fork for it?
(My branch also merges master in, because why not. Few changes there but
nothing else breaks as far as I've seen in testing.)

Could I just rebase from master and apply your commit?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/bundler/gemstash/pull/159#issuecomment-332256283>, or mute
the thread

**Comment by sk-jlewis** [comment]
@caius rebased from upstream/master and applied your fix.  Thanks for the 🦈 👁

**Comment by sk-jlewis** [comment]
@caius I'm having a hard time trying to figure out why these tests are failing in web_spec after rebasing :/  any bandwidth to collaborate?

**Comment by NobodysNightmare** [comment]
Hey there,
what's blocking this PR at the moment? Is it only the failing specs or are there further concerns?
I would be willing to investigate and try to fix remaining problems (e.g. failing specs), but since I will be doing this during my worktime, it would be useful to have an idea of what's currently missing.

We would be super happy to see this as an official feature of gemstash.

**Comment by indirect** [comment]
@NobodysNightmare if you want to get this green, I think it should be mergeable! Thanks for checking on it. :)

**Comment by CpuID** [comment]
We have been running this PR for internal production use for a few months now, haven't hit any major walls.

**Comment by sk-jlewis** [comment]
Same here, I haven't had another chance to look again at these tests, I can try to set some time again this week coming week.  

We've been using it since about August or September of last year without issue.  Happy to see some interest in this PR and would be happy to collaborate to get it over the finish line

**Comment by caius** [comment]
We've been running this internally and leaning on it moderately heavily for a couple of months now. We're only using it as an internal gem server though (`…/private`) not as a caching layer. The one change I wanted to try and add in (but haven't had time to yet) was using S3 as the backend for private gems, but not as the storage adapter for the caching of upstream `.gem` files from rubygems. We run two instances of gemstash in different sites in an active/failover pattern, with S3 providing the sync for internal gem artifacts. We don't care about the upstream `.gem` files only being cached on the local machine rather than S3 though. (It cuts out a roundtrip to S3 when first fetching a gem basically.)

That said aside from the feature request I really need to look at adding myself, this branch has been working fine for us with multiple developer workstations and app servers hitting it every day.

**Comment by indirect** [comment]
Oh! That’s a really good point. I think we will need to do one of two things before landing this:

Option 1: Only consult the config file to choose the backend for private gems, and always use disk for passthrough cache gems

Option 2: Add a second config for passthrough cache storage, defaulting to disk

Either way, it’s great to hear that this PR is working for private gems on S3!

**Comment by adamvduke** [comment]
@CpuID @sk-jlewis Do you mind sharing what database you're using? I've been working on standing this up in production. Things are more or less stable except I see somewhat regular errors related to mysql connection errors. The S3 stuff seems solid.

**Comment by caius** [comment]
@adamvduke we're using MySQL 5.6 with it successfully in production and this branch here.

**Comment by CpuID** [comment]
@adamvduke using MySQL 5.7.19 (RDS) here, we were on 5.5.x when we first started out. We don't heavily use the registry right now, but it's running and not erroring, I'd say if you have specific errors - share them in a gist just incase.

**Comment by bronzdoc** [comment]
Closing this since a S3 backend was added in https://github.com/rubygems/gemstash/pull/270 thanks!

**Pull request closed without merging**
